FROM node:20-slim

RUN corepack enable && corepack prepare pnpm@8.15.0 --activate

WORKDIR /app

ENV NODE_ENV=production

COPY . .

RUN pnpm install --frozen-lockfile

RUN pnpm --filter @aninda/shared build && \
    pnpm --filter @aninda/database build && \
    pnpm --filter @aninda/email-client build && \
    pnpm --filter @aninda/api build

EXPOSE 3001

CMD ["node", "apps/api/dist/main.js"]
