/**
 * Country → Language mapping for Smart Template localization.
 * Covers ~100 countries via both ISO 2-letter codes and full names.
 */

const COUNTRY_LANGUAGE_MAP: Record<string, string> = {
  // North America
  US: 'English',
  'UNITED STATES': 'English',
  CA: 'English',
  CANADA: 'English',
  MX: 'Spanish',
  MEXICO: 'Spanish',

  // Central America & Caribbean
  GT: 'Spanish',
  GUATEMALA: 'Spanish',
  HN: 'Spanish',
  HONDURAS: 'Spanish',
  SV: 'Spanish',
  'EL SALVADOR': 'Spanish',
  NI: 'Spanish',
  NICARAGUA: 'Spanish',
  CR: 'Spanish',
  'COSTA RICA': 'Spanish',
  PA: 'Spanish',
  PANAMA: 'Spanish',
  CU: 'Spanish',
  CUBA: 'Spanish',
  DO: 'Spanish',
  'DOMINICAN REPUBLIC': 'Spanish',
  JM: 'English',
  JAMAICA: 'English',
  HT: 'French',
  HAITI: 'French',
  PR: 'Spanish',
  'PUERTO RICO': 'Spanish',

  // South America
  BR: 'Portuguese',
  BRAZIL: 'Portuguese',
  AR: 'Spanish',
  ARGENTINA: 'Spanish',
  CO: 'Spanish',
  COLOMBIA: 'Spanish',
  CL: 'Spanish',
  CHILE: 'Spanish',
  PE: 'Spanish',
  PERU: 'Spanish',
  VE: 'Spanish',
  VENEZUELA: 'Spanish',
  EC: 'Spanish',
  ECUADOR: 'Spanish',
  BO: 'Spanish',
  BOLIVIA: 'Spanish',
  PY: 'Spanish',
  PARAGUAY: 'Spanish',
  UY: 'Spanish',
  URUGUAY: 'Spanish',

  // Western Europe
  GB: 'English',
  'UNITED KINGDOM': 'English',
  UK: 'English',
  DE: 'German',
  GERMANY: 'German',
  FR: 'French',
  FRANCE: 'French',
  ES: 'Spanish',
  SPAIN: 'Spanish',
  IT: 'Italian',
  ITALY: 'Italian',
  PT: 'Portuguese',
  PORTUGAL: 'Portuguese',
  NL: 'Dutch',
  NETHERLANDS: 'Dutch',
  BE: 'Dutch',
  BELGIUM: 'Dutch',
  AT: 'German',
  AUSTRIA: 'German',
  CH: 'German',
  SWITZERLAND: 'German',
  IE: 'English',
  IRELAND: 'English',
  LU: 'French',
  LUXEMBOURG: 'French',

  // Northern Europe
  SE: 'Swedish',
  SWEDEN: 'Swedish',
  NO: 'Norwegian',
  NORWAY: 'Norwegian',
  DK: 'Danish',
  DENMARK: 'Danish',
  FI: 'Finnish',
  FINLAND: 'Finnish',
  IS: 'Icelandic',
  ICELAND: 'Icelandic',

  // Eastern Europe
  PL: 'Polish',
  POLAND: 'Polish',
  CZ: 'Czech',
  CZECHIA: 'Czech',
  'CZECH REPUBLIC': 'Czech',
  SK: 'Slovak',
  SLOVAKIA: 'Slovak',
  HU: 'Hungarian',
  HUNGARY: 'Hungarian',
  RO: 'Romanian',
  ROMANIA: 'Romanian',
  BG: 'Bulgarian',
  BULGARIA: 'Bulgarian',
  UA: 'Ukrainian',
  UKRAINE: 'Ukrainian',
  RU: 'Russian',
  RUSSIA: 'Russian',
  BY: 'Belarusian',
  BELARUS: 'Belarusian',
  MD: 'Romanian',
  MOLDOVA: 'Romanian',

  // Baltic States
  LT: 'Lithuanian',
  LITHUANIA: 'Lithuanian',
  LV: 'Latvian',
  LATVIA: 'Latvian',
  EE: 'Estonian',
  ESTONIA: 'Estonian',

  // Balkans
  HR: 'Croatian',
  CROATIA: 'Croatian',
  RS: 'Serbian',
  SERBIA: 'Serbian',
  SI: 'Slovenian',
  SLOVENIA: 'Slovenian',
  BA: 'Bosnian',
  'BOSNIA AND HERZEGOVINA': 'Bosnian',
  ME: 'Montenegrin',
  MONTENEGRO: 'Montenegrin',
  MK: 'Macedonian',
  'NORTH MACEDONIA': 'Macedonian',
  AL: 'Albanian',
  ALBANIA: 'Albanian',
  GR: 'Greek',
  GREECE: 'Greek',

  // Middle East
  TR: 'Turkish',
  TURKEY: 'Turkish',
  IL: 'Hebrew',
  ISRAEL: 'Hebrew',
  SA: 'Arabic',
  'SAUDI ARABIA': 'Arabic',
  AE: 'Arabic',
  'UNITED ARAB EMIRATES': 'Arabic',
  QA: 'Arabic',
  QATAR: 'Arabic',
  KW: 'Arabic',
  KUWAIT: 'Arabic',
  BH: 'Arabic',
  BAHRAIN: 'Arabic',
  OM: 'Arabic',
  OMAN: 'Arabic',
  JO: 'Arabic',
  JORDAN: 'Arabic',
  LB: 'Arabic',
  LEBANON: 'Arabic',
  IQ: 'Arabic',
  IRAQ: 'Arabic',
  IR: 'Persian',
  IRAN: 'Persian',

  // South Asia
  IN: 'Hindi',
  INDIA: 'Hindi',
  PK: 'Urdu',
  PAKISTAN: 'Urdu',
  BD: 'Bengali',
  BANGLADESH: 'Bengali',
  LK: 'Sinhala',
  'SRI LANKA': 'Sinhala',
  NP: 'Nepali',
  NEPAL: 'Nepali',

  // East Asia
  CN: 'Chinese',
  CHINA: 'Chinese',
  JP: 'Japanese',
  JAPAN: 'Japanese',
  KR: 'Korean',
  'SOUTH KOREA': 'Korean',
  TW: 'Chinese',
  TAIWAN: 'Chinese',
  HK: 'Chinese',
  'HONG KONG': 'Chinese',
  MN: 'Mongolian',
  MONGOLIA: 'Mongolian',

  // Southeast Asia
  TH: 'Thai',
  THAILAND: 'Thai',
  VN: 'Vietnamese',
  VIETNAM: 'Vietnamese',
  ID: 'Indonesian',
  INDONESIA: 'Indonesian',
  MY: 'Malay',
  MALAYSIA: 'Malay',
  PH: 'Filipino',
  PHILIPPINES: 'Filipino',
  SG: 'English',
  SINGAPORE: 'English',
  MM: 'Burmese',
  MYANMAR: 'Burmese',
  KH: 'Khmer',
  CAMBODIA: 'Khmer',

  // Africa
  EG: 'Arabic',
  EGYPT: 'Arabic',
  NG: 'English',
  NIGERIA: 'English',
  ZA: 'English',
  'SOUTH AFRICA': 'English',
  KE: 'English',
  KENYA: 'English',
  GH: 'English',
  GHANA: 'English',
  ET: 'Amharic',
  ETHIOPIA: 'Amharic',
  TZ: 'Swahili',
  TANZANIA: 'Swahili',
  MA: 'Arabic',
  MOROCCO: 'Arabic',
  DZ: 'Arabic',
  ALGERIA: 'Arabic',
  TN: 'Arabic',
  TUNISIA: 'Arabic',
  SN: 'French',
  SENEGAL: 'French',
  CI: 'French',
  'IVORY COAST': 'French',
  CM: 'French',
  CAMEROON: 'French',
  UG: 'English',
  UGANDA: 'English',
  RW: 'Kinyarwanda',
  RWANDA: 'Kinyarwanda',

  // Oceania
  AU: 'English',
  AUSTRALIA: 'English',
  NZ: 'English',
  'NEW ZEALAND': 'English',

  // Central Asia
  KZ: 'Kazakh',
  KAZAKHSTAN: 'Kazakh',
  UZ: 'Uzbek',
  UZBEKISTAN: 'Uzbek',
  GE: 'Georgian',
  GEORGIA: 'Georgian',
  AZ: 'Azerbaijani',
  AZERBAIJAN: 'Azerbaijani',
  AM: 'Armenian',
  ARMENIA: 'Armenian',
};

/**
 * Get the primary language for a country.
 * Accepts ISO 2-letter codes ("US", "DE") or full names ("United States", "Germany").
 * Case-insensitive. Falls back to 'English' for null, undefined, or unknown values.
 */
export function getLanguageFromCountry(country: string | null | undefined): string {
  if (!country) return 'English';
  const key = country.trim().toUpperCase();
  return COUNTRY_LANGUAGE_MAP[key] || 'English';
}
