export type Json = string | number | boolean | null | {
    [key: string]: Json | undefined;
} | Json[];
export type Database = {
    public: {
        Tables: {
            teams: {
                Row: {
                    id: string;
                    name: string;
                    slug: string;
                    plan: 'free' | 'starter' | 'pro' | 'enterprise';
                    stripe_customer_id: string | null;
                    stripe_subscription_id: string | null;
                    daily_email_limit: number;
                    max_inboxes: number;
                    max_campaigns: number;
                    max_team_members: number;
                    physical_address: string | null;
                    company_name: string | null;
                    settings: Json;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    name: string;
                    slug: string;
                    plan?: 'free' | 'starter' | 'pro' | 'enterprise';
                    stripe_customer_id?: string | null;
                    stripe_subscription_id?: string | null;
                    daily_email_limit?: number;
                    max_inboxes?: number;
                    max_campaigns?: number;
                    max_team_members?: number;
                    physical_address?: string | null;
                    company_name?: string | null;
                    settings?: Json;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    name?: string;
                    slug?: string;
                    plan?: 'free' | 'starter' | 'pro' | 'enterprise';
                    stripe_customer_id?: string | null;
                    stripe_subscription_id?: string | null;
                    daily_email_limit?: number;
                    max_inboxes?: number;
                    max_campaigns?: number;
                    max_team_members?: number;
                    physical_address?: string | null;
                    company_name?: string | null;
                    settings?: Json;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            users: {
                Row: {
                    id: string;
                    email: string;
                    full_name: string | null;
                    avatar_url: string | null;
                    timezone: string;
                    notification_preferences: Json;
                    last_active_at: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id: string;
                    email: string;
                    full_name?: string | null;
                    avatar_url?: string | null;
                    timezone?: string;
                    notification_preferences?: Json;
                    last_active_at?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    email?: string;
                    full_name?: string | null;
                    avatar_url?: string | null;
                    timezone?: string;
                    notification_preferences?: Json;
                    last_active_at?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            team_members: {
                Row: {
                    id: string;
                    team_id: string;
                    user_id: string;
                    role: 'owner' | 'admin' | 'member' | 'viewer';
                    invited_by: string | null;
                    invited_at: string | null;
                    accepted_at: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    team_id: string;
                    user_id: string;
                    role?: 'owner' | 'admin' | 'member' | 'viewer';
                    invited_by?: string | null;
                    invited_at?: string | null;
                    accepted_at?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    team_id?: string;
                    user_id?: string;
                    role?: 'owner' | 'admin' | 'member' | 'viewer';
                    invited_by?: string | null;
                    invited_at?: string | null;
                    accepted_at?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            domains: {
                Row: {
                    id: string;
                    team_id: string;
                    domain: string;
                    spf_valid: boolean;
                    spf_record: string | null;
                    dkim_valid: boolean;
                    dkim_selector: string | null;
                    dkim_record: string | null;
                    dmarc_valid: boolean;
                    dmarc_policy: string | null;
                    dmarc_record: string | null;
                    health_score: number;
                    last_checked_at: string | null;
                    verified_at: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    team_id: string;
                    domain: string;
                    spf_valid?: boolean;
                    spf_record?: string | null;
                    dkim_valid?: boolean;
                    dkim_selector?: string | null;
                    dkim_record?: string | null;
                    dmarc_valid?: boolean;
                    dmarc_policy?: string | null;
                    dmarc_record?: string | null;
                    health_score?: number;
                    last_checked_at?: string | null;
                    verified_at?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    team_id?: string;
                    domain?: string;
                    spf_valid?: boolean;
                    spf_record?: string | null;
                    dkim_valid?: boolean;
                    dkim_selector?: string | null;
                    dkim_record?: string | null;
                    dmarc_valid?: boolean;
                    dmarc_policy?: string | null;
                    dmarc_record?: string | null;
                    health_score?: number;
                    last_checked_at?: string | null;
                    verified_at?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            inboxes: {
                Row: {
                    id: string;
                    team_id: string;
                    domain_id: string | null;
                    email: string;
                    from_name: string | null;
                    provider: 'google' | 'microsoft' | 'smtp';
                    status: 'active' | 'paused' | 'error' | 'warming_up' | 'banned';
                    status_reason: string | null;
                    paused_at: string | null;
                    oauth_access_token: string | null;
                    oauth_refresh_token: string | null;
                    oauth_expires_at: string | null;
                    oauth_scope: string | null;
                    smtp_host: string | null;
                    smtp_port: number | null;
                    smtp_username: string | null;
                    smtp_password: string | null;
                    imap_host: string | null;
                    imap_port: number | null;
                    health_score: number;
                    bounce_rate_7d: number;
                    open_rate_7d: number;
                    reply_rate_7d: number;
                    sent_today: number;
                    sent_this_week: number;
                    sent_total: number;
                    daily_send_limit: number;
                    throttle_percentage: number;
                    circuit_state: 'closed' | 'open' | 'half-open';
                    circuit_failure_count: number;
                    circuit_last_failure_at: string | null;
                    last_sent_at: string | null;
                    spam_complaints_total: number;
                    last_reply_checked_at: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    team_id: string;
                    domain_id?: string | null;
                    email: string;
                    from_name?: string | null;
                    provider: 'google' | 'microsoft' | 'smtp';
                    status?: 'active' | 'paused' | 'error' | 'warming_up' | 'banned';
                    status_reason?: string | null;
                    paused_at?: string | null;
                    oauth_access_token?: string | null;
                    oauth_refresh_token?: string | null;
                    oauth_expires_at?: string | null;
                    oauth_scope?: string | null;
                    smtp_host?: string | null;
                    smtp_port?: number | null;
                    smtp_username?: string | null;
                    smtp_password?: string | null;
                    imap_host?: string | null;
                    imap_port?: number | null;
                    health_score?: number;
                    bounce_rate_7d?: number;
                    open_rate_7d?: number;
                    reply_rate_7d?: number;
                    sent_today?: number;
                    sent_this_week?: number;
                    sent_total?: number;
                    daily_send_limit?: number;
                    throttle_percentage?: number;
                    circuit_state?: 'closed' | 'open' | 'half-open';
                    circuit_failure_count?: number;
                    circuit_last_failure_at?: string | null;
                    last_sent_at?: string | null;
                    spam_complaints_total?: number;
                    last_reply_checked_at?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    team_id?: string;
                    domain_id?: string | null;
                    email?: string;
                    from_name?: string | null;
                    provider?: 'google' | 'microsoft' | 'smtp';
                    status?: 'active' | 'paused' | 'error' | 'warming_up' | 'banned';
                    status_reason?: string | null;
                    paused_at?: string | null;
                    oauth_access_token?: string | null;
                    oauth_refresh_token?: string | null;
                    oauth_expires_at?: string | null;
                    oauth_scope?: string | null;
                    smtp_host?: string | null;
                    smtp_port?: number | null;
                    smtp_username?: string | null;
                    smtp_password?: string | null;
                    imap_host?: string | null;
                    imap_port?: number | null;
                    health_score?: number;
                    bounce_rate_7d?: number;
                    open_rate_7d?: number;
                    reply_rate_7d?: number;
                    sent_today?: number;
                    sent_this_week?: number;
                    sent_total?: number;
                    daily_send_limit?: number;
                    throttle_percentage?: number;
                    circuit_state?: 'closed' | 'open' | 'half-open';
                    circuit_failure_count?: number;
                    circuit_last_failure_at?: string | null;
                    last_sent_at?: string | null;
                    spam_complaints_total?: number;
                    last_reply_checked_at?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            inbox_settings: {
                Row: {
                    id: string;
                    inbox_id: string;
                    daily_send_limit: number;
                    hourly_limit: number;
                    min_delay_seconds: number;
                    max_delay_seconds: number;
                    send_window_start: string;
                    send_window_end: string;
                    send_window_timezone: string;
                    send_days: string[];
                    weekends_enabled: boolean;
                    esp_matching_enabled: boolean;
                    auto_throttle_enabled: boolean;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    inbox_id: string;
                    daily_send_limit?: number;
                    hourly_limit?: number;
                    min_delay_seconds?: number;
                    max_delay_seconds?: number;
                    send_window_start?: string;
                    send_window_end?: string;
                    send_window_timezone?: string;
                    send_days?: string[];
                    weekends_enabled?: boolean;
                    esp_matching_enabled?: boolean;
                    auto_throttle_enabled?: boolean;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    inbox_id?: string;
                    daily_send_limit?: number;
                    hourly_limit?: number;
                    min_delay_seconds?: number;
                    max_delay_seconds?: number;
                    send_window_start?: string;
                    send_window_end?: string;
                    send_window_timezone?: string;
                    send_days?: string[];
                    weekends_enabled?: boolean;
                    esp_matching_enabled?: boolean;
                    auto_throttle_enabled?: boolean;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            warmup_state: {
                Row: {
                    id: string;
                    inbox_id: string;
                    enabled: boolean;
                    phase: 'ramping' | 'maintaining' | 'paused' | 'completed';
                    started_at: string | null;
                    current_day: number;
                    ramp_speed: 'slow' | 'normal' | 'fast';
                    target_daily_volume: number;
                    reply_rate_target: number;
                    sent_today: number;
                    received_today: number;
                    replied_today: number;
                    sent_total: number;
                    received_total: number;
                    replied_total: number;
                    spam_today: number;
                    spam_total: number;
                    last_activity_at: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    inbox_id: string;
                    enabled?: boolean;
                    phase?: 'ramping' | 'maintaining' | 'paused' | 'completed';
                    started_at?: string | null;
                    current_day?: number;
                    ramp_speed?: 'slow' | 'normal' | 'fast';
                    target_daily_volume?: number;
                    reply_rate_target?: number;
                    sent_today?: number;
                    received_today?: number;
                    replied_today?: number;
                    sent_total?: number;
                    received_total?: number;
                    replied_total?: number;
                    spam_today?: number;
                    spam_total?: number;
                    last_activity_at?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    inbox_id?: string;
                    enabled?: boolean;
                    phase?: 'ramping' | 'maintaining' | 'paused' | 'completed';
                    started_at?: string | null;
                    current_day?: number;
                    ramp_speed?: 'slow' | 'normal' | 'fast';
                    target_daily_volume?: number;
                    reply_rate_target?: number;
                    sent_today?: number;
                    received_today?: number;
                    replied_today?: number;
                    sent_total?: number;
                    received_total?: number;
                    replied_total?: number;
                    spam_today?: number;
                    spam_total?: number;
                    last_activity_at?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            warmup_interactions: {
                Row: {
                    id: string;
                    from_inbox_id: string;
                    to_inbox_id: string;
                    interaction_type: 'sent' | 'received' | 'replied' | 'opened' | 'starred';
                    message_id: string | null;
                    thread_id: string | null;
                    subject: string | null;
                    thread_depth: number | null;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    from_inbox_id: string;
                    to_inbox_id: string;
                    interaction_type: 'sent' | 'received' | 'replied' | 'opened' | 'starred';
                    message_id?: string | null;
                    thread_id?: string | null;
                    subject?: string | null;
                    thread_depth?: number | null;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    from_inbox_id?: string;
                    to_inbox_id?: string;
                    interaction_type?: 'sent' | 'received' | 'replied' | 'opened' | 'starred';
                    message_id?: string | null;
                    thread_id?: string | null;
                    subject?: string | null;
                    thread_depth?: number | null;
                    created_at?: string;
                };
            };
            lead_lists: {
                Row: {
                    id: string;
                    team_id: string;
                    name: string;
                    description: string | null;
                    lead_count: number;
                    source: string | null;
                    imported_at: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    team_id: string;
                    name: string;
                    description?: string | null;
                    lead_count?: number;
                    source?: string | null;
                    imported_at?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    team_id?: string;
                    name?: string;
                    description?: string | null;
                    lead_count?: number;
                    source?: string | null;
                    imported_at?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            leads: {
                Row: {
                    id: string;
                    team_id: string;
                    lead_list_id: string | null;
                    email: string;
                    first_name: string | null;
                    last_name: string | null;
                    company: string | null;
                    title: string | null;
                    phone: string | null;
                    linkedin_url: string | null;
                    website: string | null;
                    status: 'pending' | 'in_sequence' | 'contacted' | 'replied' | 'interested' | 'not_interested' | 'meeting_booked' | 'bounced' | 'soft_bounced' | 'unsubscribed' | 'spam_reported' | 'sequence_complete';
                    reply_intent: string | null;
                    timezone: string | null;
                    country: string | null;
                    city: string | null;
                    custom_fields: Json;
                    unsubscribe_token: string;
                    consent_type: string | null;
                    consent_source: string | null;
                    current_campaign_id: string | null;
                    current_step: number | null;
                    next_send_at: string | null;
                    first_contacted_at: string | null;
                    last_contacted_at: string | null;
                    replied_at: string | null;
                    bounced_at: string | null;
                    unsubscribed_at: string | null;
                    email_verification_status: 'unverified' | 'verifying' | 'valid' | 'invalid' | 'catch_all' | 'risky' | 'unknown' | null;
                    email_risk_score: number | null;
                    email_verified_at: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    team_id: string;
                    lead_list_id?: string | null;
                    email: string;
                    first_name?: string | null;
                    last_name?: string | null;
                    company?: string | null;
                    title?: string | null;
                    phone?: string | null;
                    linkedin_url?: string | null;
                    website?: string | null;
                    status?: 'pending' | 'in_sequence' | 'contacted' | 'replied' | 'interested' | 'not_interested' | 'meeting_booked' | 'bounced' | 'soft_bounced' | 'unsubscribed' | 'spam_reported' | 'sequence_complete';
                    reply_intent?: string | null;
                    timezone?: string | null;
                    country?: string | null;
                    city?: string | null;
                    custom_fields?: Json;
                    unsubscribe_token?: string;
                    consent_type?: string | null;
                    consent_source?: string | null;
                    current_campaign_id?: string | null;
                    current_step?: number | null;
                    next_send_at?: string | null;
                    first_contacted_at?: string | null;
                    last_contacted_at?: string | null;
                    replied_at?: string | null;
                    bounced_at?: string | null;
                    unsubscribed_at?: string | null;
                    email_verification_status?: 'unverified' | 'verifying' | 'valid' | 'invalid' | 'catch_all' | 'risky' | 'unknown' | null;
                    email_risk_score?: number | null;
                    email_verified_at?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    team_id?: string;
                    lead_list_id?: string | null;
                    email?: string;
                    first_name?: string | null;
                    last_name?: string | null;
                    company?: string | null;
                    title?: string | null;
                    phone?: string | null;
                    linkedin_url?: string | null;
                    website?: string | null;
                    status?: 'pending' | 'in_sequence' | 'contacted' | 'replied' | 'interested' | 'not_interested' | 'meeting_booked' | 'bounced' | 'soft_bounced' | 'unsubscribed' | 'spam_reported' | 'sequence_complete';
                    reply_intent?: string | null;
                    timezone?: string | null;
                    country?: string | null;
                    city?: string | null;
                    custom_fields?: Json;
                    unsubscribe_token?: string;
                    consent_type?: string | null;
                    consent_source?: string | null;
                    current_campaign_id?: string | null;
                    current_step?: number | null;
                    next_send_at?: string | null;
                    first_contacted_at?: string | null;
                    last_contacted_at?: string | null;
                    replied_at?: string | null;
                    bounced_at?: string | null;
                    unsubscribed_at?: string | null;
                    email_verification_status?: 'unverified' | 'verifying' | 'valid' | 'invalid' | 'catch_all' | 'risky' | 'unknown' | null;
                    email_risk_score?: number | null;
                    email_verified_at?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            campaigns: {
                Row: {
                    id: string;
                    team_id: string;
                    lead_list_id: string | null;
                    name: string;
                    description: string | null;
                    status: 'draft' | 'scheduled' | 'active' | 'paused' | 'completed' | 'archived';
                    settings: Json;
                    lead_count: number;
                    sent_count: number;
                    delivered_count: number;
                    opened_count: number;
                    clicked_count: number;
                    replied_count: number;
                    bounced_count: number;
                    unsubscribed_count: number;
                    scheduled_start_at: string | null;
                    started_at: string | null;
                    completed_at: string | null;
                    paused_at: string | null;
                    created_by: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    team_id: string;
                    lead_list_id?: string | null;
                    name: string;
                    description?: string | null;
                    status?: 'draft' | 'scheduled' | 'active' | 'paused' | 'completed' | 'archived';
                    settings?: Json;
                    lead_count?: number;
                    sent_count?: number;
                    delivered_count?: number;
                    opened_count?: number;
                    clicked_count?: number;
                    replied_count?: number;
                    bounced_count?: number;
                    unsubscribed_count?: number;
                    scheduled_start_at?: string | null;
                    started_at?: string | null;
                    completed_at?: string | null;
                    paused_at?: string | null;
                    created_by?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    team_id?: string;
                    lead_list_id?: string | null;
                    name?: string;
                    description?: string | null;
                    status?: 'draft' | 'scheduled' | 'active' | 'paused' | 'completed' | 'archived';
                    settings?: Json;
                    lead_count?: number;
                    sent_count?: number;
                    delivered_count?: number;
                    opened_count?: number;
                    clicked_count?: number;
                    replied_count?: number;
                    bounced_count?: number;
                    unsubscribed_count?: number;
                    scheduled_start_at?: string | null;
                    started_at?: string | null;
                    completed_at?: string | null;
                    paused_at?: string | null;
                    created_by?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            sequences: {
                Row: {
                    id: string;
                    campaign_id: string;
                    step_number: number;
                    delay_days: number;
                    delay_hours: number;
                    subject: string;
                    body: string;
                    conditions: Json;
                    sent_count: number;
                    opened_count: number;
                    replied_count: number;
                    smart_template_language_match: boolean;
                    smart_template_notes: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    campaign_id: string;
                    step_number: number;
                    delay_days?: number;
                    delay_hours?: number;
                    subject: string;
                    body: string;
                    conditions?: Json;
                    sent_count?: number;
                    opened_count?: number;
                    replied_count?: number;
                    smart_template_language_match?: boolean;
                    smart_template_notes?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    campaign_id?: string;
                    step_number?: number;
                    delay_days?: number;
                    delay_hours?: number;
                    subject?: string;
                    body?: string;
                    conditions?: Json;
                    sent_count?: number;
                    opened_count?: number;
                    replied_count?: number;
                    smart_template_language_match?: boolean;
                    smart_template_notes?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            campaign_inboxes: {
                Row: {
                    id: string;
                    campaign_id: string;
                    inbox_id: string;
                    sent_count: number;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    campaign_id: string;
                    inbox_id: string;
                    sent_count?: number;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    campaign_id?: string;
                    inbox_id?: string;
                    sent_count?: number;
                    created_at?: string;
                };
            };
            emails: {
                Row: {
                    id: string;
                    team_id: string;
                    campaign_id: string | null;
                    sequence_id: string | null;
                    sequence_step: number | null;
                    variant_id: string | null;
                    lead_id: string;
                    inbox_id: string;
                    message_id: string | null;
                    thread_id: string | null;
                    in_reply_to: string | null;
                    references_header: string | null;
                    from_email: string;
                    from_name: string | null;
                    to_email: string;
                    subject: string;
                    body_html: string | null;
                    body_text: string | null;
                    status: 'queued' | 'sending' | 'sent' | 'delivered' | 'opened' | 'clicked' | 'bounced' | 'failed';
                    error_message: string | null;
                    open_tracked: boolean;
                    click_tracked: boolean;
                    open_count: number;
                    click_count: number;
                    scheduled_at: string | null;
                    sent_at: string | null;
                    delivered_at: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    team_id: string;
                    campaign_id?: string | null;
                    sequence_id?: string | null;
                    sequence_step?: number | null;
                    variant_id?: string | null;
                    lead_id: string;
                    inbox_id: string;
                    message_id?: string | null;
                    thread_id?: string | null;
                    in_reply_to?: string | null;
                    references_header?: string | null;
                    from_email: string;
                    from_name?: string | null;
                    to_email: string;
                    subject: string;
                    body_html?: string | null;
                    body_text?: string | null;
                    status?: 'queued' | 'sending' | 'sent' | 'delivered' | 'opened' | 'clicked' | 'bounced' | 'failed';
                    error_message?: string | null;
                    open_tracked?: boolean;
                    click_tracked?: boolean;
                    open_count?: number;
                    click_count?: number;
                    scheduled_at?: string | null;
                    sent_at?: string | null;
                    delivered_at?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    team_id?: string;
                    campaign_id?: string | null;
                    sequence_id?: string | null;
                    sequence_step?: number | null;
                    variant_id?: string | null;
                    lead_id?: string;
                    inbox_id?: string;
                    message_id?: string | null;
                    thread_id?: string | null;
                    in_reply_to?: string | null;
                    references_header?: string | null;
                    from_email?: string;
                    from_name?: string | null;
                    to_email?: string;
                    subject?: string;
                    body_html?: string | null;
                    body_text?: string | null;
                    status?: 'queued' | 'sending' | 'sent' | 'delivered' | 'opened' | 'clicked' | 'bounced' | 'failed';
                    error_message?: string | null;
                    open_tracked?: boolean;
                    click_tracked?: boolean;
                    open_count?: number;
                    click_count?: number;
                    scheduled_at?: string | null;
                    sent_at?: string | null;
                    delivered_at?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            replies: {
                Row: {
                    id: string;
                    team_id: string;
                    email_id: string | null;
                    lead_id: string;
                    inbox_id: string;
                    campaign_id: string | null;
                    message_id: string | null;
                    thread_id: string | null;
                    in_reply_to: string | null;
                    from_email: string;
                    from_name: string | null;
                    subject: string | null;
                    body_html: string | null;
                    body_text: string | null;
                    body_preview: string | null;
                    intent: 'interested' | 'meeting_request' | 'question' | 'not_interested' | 'unsubscribe' | 'out_of_office' | 'auto_reply' | 'bounce' | 'neutral' | null;
                    intent_confidence: number | null;
                    intent_model: string | null;
                    intent_manual_override: boolean;
                    is_read: boolean;
                    is_archived: boolean;
                    received_at: string;
                    read_at: string | null;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    team_id: string;
                    email_id?: string | null;
                    lead_id: string;
                    inbox_id: string;
                    campaign_id?: string | null;
                    message_id?: string | null;
                    thread_id?: string | null;
                    in_reply_to?: string | null;
                    from_email: string;
                    from_name?: string | null;
                    subject?: string | null;
                    body_html?: string | null;
                    body_text?: string | null;
                    body_preview?: string | null;
                    intent?: 'interested' | 'meeting_request' | 'question' | 'not_interested' | 'unsubscribe' | 'out_of_office' | 'auto_reply' | 'bounce' | 'neutral' | null;
                    intent_confidence?: number | null;
                    intent_model?: string | null;
                    intent_manual_override?: boolean;
                    is_read?: boolean;
                    is_archived?: boolean;
                    received_at: string;
                    read_at?: string | null;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    team_id?: string;
                    email_id?: string | null;
                    lead_id?: string;
                    inbox_id?: string;
                    campaign_id?: string | null;
                    message_id?: string | null;
                    thread_id?: string | null;
                    in_reply_to?: string | null;
                    from_email?: string;
                    from_name?: string | null;
                    subject?: string | null;
                    body_html?: string | null;
                    body_text?: string | null;
                    body_preview?: string | null;
                    intent?: 'interested' | 'meeting_request' | 'question' | 'not_interested' | 'unsubscribe' | 'out_of_office' | 'auto_reply' | 'bounce' | 'neutral' | null;
                    intent_confidence?: number | null;
                    intent_model?: string | null;
                    intent_manual_override?: boolean;
                    is_read?: boolean;
                    is_archived?: boolean;
                    received_at?: string;
                    read_at?: string | null;
                    created_at?: string;
                };
            };
            sent_replies: {
                Row: {
                    id: string;
                    team_id: string;
                    reply_id: string;
                    inbox_id: string;
                    lead_id: string | null;
                    campaign_id: string | null;
                    subject: string | null;
                    body_html: string;
                    body_text: string | null;
                    message_id: string | null;
                    in_reply_to: string | null;
                    thread_id: string | null;
                    references_header: string | null;
                    status: 'queued' | 'sending' | 'sent' | 'failed' | 'bounced';
                    error_message: string | null;
                    sent_at: string;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    team_id: string;
                    reply_id: string;
                    inbox_id: string;
                    lead_id?: string | null;
                    campaign_id?: string | null;
                    subject?: string | null;
                    body_html: string;
                    body_text?: string | null;
                    message_id?: string | null;
                    in_reply_to?: string | null;
                    thread_id?: string | null;
                    references_header?: string | null;
                    status?: 'queued' | 'sending' | 'sent' | 'failed' | 'bounced';
                    error_message?: string | null;
                    sent_at?: string;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    team_id?: string;
                    reply_id?: string;
                    inbox_id?: string;
                    lead_id?: string | null;
                    campaign_id?: string | null;
                    subject?: string | null;
                    body_html?: string;
                    body_text?: string | null;
                    message_id?: string | null;
                    in_reply_to?: string | null;
                    thread_id?: string | null;
                    references_header?: string | null;
                    status?: 'queued' | 'sending' | 'sent' | 'failed' | 'bounced';
                    error_message?: string | null;
                    sent_at?: string;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            sequence_variants: {
                Row: {
                    id: string;
                    sequence_id: string;
                    variant_index: number;
                    variant_name: string | null;
                    subject: string;
                    body: string;
                    weight: number;
                    sent_count: number;
                    opened_count: number;
                    clicked_count: number;
                    replied_count: number;
                    is_winner: boolean;
                    winner_declared_at: string | null;
                    smart_template_language_match: boolean;
                    smart_template_notes: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    sequence_id: string;
                    variant_index?: number;
                    variant_name?: string | null;
                    subject: string;
                    body: string;
                    weight?: number;
                    sent_count?: number;
                    opened_count?: number;
                    clicked_count?: number;
                    replied_count?: number;
                    is_winner?: boolean;
                    winner_declared_at?: string | null;
                    smart_template_language_match?: boolean;
                    smart_template_notes?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    sequence_id?: string;
                    variant_index?: number;
                    variant_name?: string | null;
                    subject?: string;
                    body?: string;
                    weight?: number;
                    sent_count?: number;
                    opened_count?: number;
                    clicked_count?: number;
                    replied_count?: number;
                    is_winner?: boolean;
                    winner_declared_at?: string | null;
                    smart_template_language_match?: boolean;
                    smart_template_notes?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            ab_test_events: {
                Row: {
                    id: string;
                    team_id: string;
                    campaign_id: string;
                    sequence_id: string;
                    event_type: string;
                    winner_variant_id: string | null;
                    metric: string | null;
                    confidence: number | null;
                    metadata: Json;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    team_id: string;
                    campaign_id: string;
                    sequence_id: string;
                    event_type: string;
                    winner_variant_id?: string | null;
                    metric?: string | null;
                    confidence?: number | null;
                    metadata?: Json;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    team_id?: string;
                    campaign_id?: string;
                    sequence_id?: string;
                    event_type?: string;
                    winner_variant_id?: string | null;
                    metric?: string | null;
                    confidence?: number | null;
                    metadata?: Json;
                    created_at?: string;
                };
            };
        };
        Views: {};
        Functions: {};
        Enums: {};
    };
};
